### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by DavidGpro** [PichotM/pPhone2#3]
Hi, how can I see it in html?

**Comment by PichotM** [comment]
https://reactjs.org/

**Comment by DavidGpro** [comment]
How I do this ?

**Comment by YohannFin** [comment]
You can just clone the project with `git clone`, use `npm install` and run the project with `npm run dev`

**Comment by DavidGpro** [comment]
Write me in discord David G pro#8961. Please

**Comment by YohannFin** [comment]
No i don't have time, just follow what i said and search on google. Have a good day.

**Comment by DavidGpro** [comment]
And you
