### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by DatMayo** [PichotM/pPhone2#8]
Hey,

just found your project and I've got some questions:

- why you're using @types/jest? You don't have any jest config
- why you're using pug & react
- why you've typescript and prettier as "normal" dependencies

**Comment by PichotM** [comment]
Jest is probably a left-over
TS & prettier outside dev dependencies are probably a mistake
and for pug & react why not

**Comment by DatMayo** [comment]
> Jest is probably a left-over
> TS & prettier outside dev dependencies are probably a mistake
No Problem, just wondering :)

> and for pug & react why not
you can do everything what pug can do with react (and many more), so why limit yourself?

**Comment by corazon2** [comment]
I like ham
